[package]
name = "which"
version = "0.2.0"
authors = ["fangyuanziti <tiziyuanfang@gmail.com>"]
repository = "https://github.com/fangyuanziti/which-rs.git"
documentation = "http://fangyuanziti.github.io/which-rs/which/"
license = "MIT"
description= "A Rust equivalent of Unix command \"which\"."

[dependencies]
libc = "0.2.10"

[dev-dependencies]
tempdir = "0.3.4"
